#!/bin/sh

AM_USERNAME=USERNAME_HERE
AM_PASSWORD=PASSWORD_HERE
AM_DEVICE_TO_MONITOR=DEVICE_NAME_HERE
AM_DEVICE_TO_POWERSAVE=DEVICE_NAME_HERE

PYTHONPATH=~/plotwatt-api/ python powersaver.py --AM_USERNAME=$AM_USERNAME --AM_PASSWORD=$AM_PASSWORD --AM_DEVICE_TO_MONITOR=$AM_DEVICE_TO_MONITOR --AM_DEVICE_TO_POWERSAVE=$AM_DEVICE_TO_POWERSAVE
